---
- name: Update ubuntu
  become: yes
  apt: update_cache=yes

- name: Install required packages
  become: yes
  apt: 
    pkg: 
      - build-essential
      - cmake
    state: present

- name: Create temp directory
  file: 
    path: "{{ gmx_temp_dir }}" 
    state: directory

- name: Untar gromacs 2018
  unarchive:
    src: http://ftp.gromacs.org/pub/gromacs/gromacs-2018.tar.gz
    dest: "{{ gmx_temp_dir }}"
    copy: no

- name: Create build directory
  file: 
    path: "{{ gmx_temp_dir }}/gromacs-2018/build" 
    state: directory

- name: Config installation with cmake
  shell: |
    cmake .. \
     -DGMX_GPU=ON \
     -DGMX_MPI=ON  \
     -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
     -DCMAKE_C_COMPILER=nvcc \
     -DCMAKE_CXX_COMPILER=mpic++ \ 
     -DCMAKE_C_COMPILER=mpicc \
     -DGMX_BUILD_OWN_FFTW=ON
  args:
    chdir: "{{ gmx_temp_dir }}/gromacs-2018/build"

- name: make, make check and make install
  shell: "{{ item }}"
  args:
    chdir: "{{ gmx_temp_dir }}/gromacs-2018/build"
  with_items:
    - make
    - make check

- name: make, make check and make install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: "{{ gmx_temp_dir }}/gromacs-2018/build"
  with_items:
    - make install

- name: Source GMXRC
  shell: source /usr/local/gromacs/bin/GMXRC
  args:
    executable: /bin/bash

- name: Create sym links
  become: yes
  file:
    src: /usr/local/gromacs/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
      - gmx_mpi

